n = input('Digite um tipo: ')
print('O tipo que você digitou foi: {}'.format(n))
print('Só tem espaços: {}'.format(n.isspace()))
print('É um número: {}'.format(n.isnumeric()))
print('É alfabético: {}'.format(n.isalpha()))
print('É alfanumerico: {}'.format(n.isalnum()))
print('Está em maiusculas: {}'.format(n.isupper()))
print('Está em minusculas: {}'.format(n.islower()))
print('Esta captalizado: {}'.format(n.istitle()))
